columns = {"Stan":
           {
            "id": "id",
            "Ime": "ime",
            "datum": "datum",
            "Cijena": "cijena",
            "Stanje": "stanje",
            "Lokacija": "lokacija",
            "lat": "lat",
            "lng": "lng",
            "Kvadrata": "kvadrata",
            "Broj soba": "broj_soba",
            "Sprat": "sprat",
            "kompanija": "kompanija",
            "Vrsta grijanja": "vrsta_grijanja",
            "Namješten?": "namjesten",
            "Kanalizacija": "kanalizacija",
            "Parking": "parking",
            "Struja": "struja",
            "Uknjiženo / ZK": "uknjizeno",
            "Voda": "voda",
            "Vrsta oglasa": "vrsta_oglasa",
            "Datum objave": "datum_objave",
            "Broj pregleda": "broj_pregleda",
            "Balkon": "balkon",
            "Blindirana vrata": "blindirana_vrata",
            "Internet": "internet",
            "Kablovska TV": "kablovska",
            "Nedavno adaptiran": "nedavno_adaptiran",
            "Plin": "plin",
            "Podrum/Tavan": "podrum",
            "Uključen trošak režija": "rezije",
            "Adresa": "adresa",
            "Godina izgradnje": "godina_izgradnje",
            "Vrsta poda": "vrsta_poda",
            "Primarna orjentacija": "primarna_orijentacija",
            "Klima": "klima",
            "Lift": "lift",
            "Telefonski priključak": "telefon",
            "Video nadzor": "video_nadzor",
            "Za studente": "za_studente",
            "Kvadratura balkona": "kvadratura_balkona",
            "Ostava/špajz": "ostava",
            "Kućni ljubimci": "kucni_ljubimci",
            "Novogradnja": "novogradnja",
            "Alarm": "alarm",
            "Garaža": "garaza",
            "Obnovljen": "obnovljen",
           },
           "Kuca":
           {
            "id": "id",
            "Ime": "ime",
            "datum": "datum",
            "Cijena": "cijena",
            "Stanje": "stanje",
            "Lokacija": "lokacija",
            "lat": "lat",
            "lng": "lng",
            "Kvadrata": "kvadrata",
            "Broj soba": "broj_soba",
            "Broj spratova": "broj_spratova",
            "kompanija": "kompanija",
            "Vrsta grijanja": "vrsta_grijanja",
            "Okućnica (kvadratura)": "okucnica_kvadratura",
            "Vrsta poda": "vrsta_poda",
            "Balkon": "balkon",
            "Iznajmljeno": "iznajmljeno",
            "Kablovska TV": "kablovska",
            "Ostava/špajz": "ostava",
            "Parking": "parking",
            "Podrum/Tavan": "podrum",
            "Struja": "struja",
            "Uknjiženo / ZK": "uknjizeno",
            "Voda": "voda",
            "Vrsta oglasa": "vrsta_oglasa",
            "Datum objave": "datum_objave",
            "Broj pregleda": "broj_pregleda",
            "Kanalizacija": "kanalizacija",
            "Alarm": "alarm",
            "Blindirana vrata": "blindirana_vrata",
            "Garaža": "garaza",
            "Internet": "internet",
            "Klima": "klima",
            "Namještena": "namjestena",
            "Nedavno adaptirana": "nedavno_adaptirana",
            "Plin": "plin",
            "Telefonski priključak": "telefon",
            "Video nadzor": "video_nadzor",
            "Adresa": "adresa",
            "Godina izgradnje": "godina_izgradnje",
            "Primarna orjentacija": "primarna_orijentacija",
            "Bazen": "bazen",
            "Obnovljen": "obnovljen",
           },
           "Zemljiste":
           {
            "id": "id",
            "Ime": "ime",
            "datum": "datum",
            "Cijena": "cijena",
            "Lokacija": "lokacija",
            "lat": "lat",
            "lng": "lng",
            "Prilaz": "prilaz",
            "Kvadrata": "kvadrata",
            "kompanija": "kompanija",
            "Komunalni priključak": "komunalni_prikljucak",
            "Uknjiženo (ZK)": "uknjizeno",
            "Vrsta oglasa": "vrsta_oglasa",
            "Datum objave": "datum_objave",
            "Broj pregleda": "broj_pregleda",
            "Udaljenost od rijeke (m)": "udaljenost_rijeka",
            "Građevinska dozvola": "gradjevinska_dozvola",
            "Urbanistička dozvola": "urbanisticka_dozvola",
            "Iznajmljeno": "iznajmljeno",
            "Obnovljen": "obnovljen",
            }
           }

radio_columns = [
    "struja",
    "voda",
    "balkon",
    "kablovska",
    "ostava",
    "parking",
    "podrum",
    "uknjizeno",
    "alarm",
    "blindirana_vrata",
    "garaza",
    "internet",
    "klima",
    "nedavno_adaptirana",
    "plin",
    "telefon",
    "video_nadzor",
    "bazen",
    "gradjevinska_dozvola",
    "urbanisticka_dozvola",
    "komunalni_prikljucak",
    "iznajmljeno",
    "lift",
    "za_studente",
    "kucni_ljubimci",
    "novogradnja",
    "nedavno_adaptiran",
    "rezije",
    "kanalizacija",
    "namjesten",
    "namjestena"
]
